CREATE TABLE [Accounting].[Customer]
(
	[Id] INT NOT NULL IDENTITY,
	[TypeId] INT NOT NULL,
	[ParentId] INT NULL,
    [CustomerName] NVARCHAR(200) NULL, 
    [CustomerLeader] NVARCHAR(200) NULL, 
    [WorkTypeId] INT NULL, 
    [Voen] NVARCHAR(50) NULL, 
    [CurrencyId] INT NULL, 
    [BankId] INT NULL, 
    [BankSwift] NVARCHAR(200) NULL, 
	[RegionId] int null,
    [LegalAddress] NVARCHAR(200) NULL, 
    [ActualAddress] NVARCHAR(200) NULL, 
    [Email] NVARCHAR(200) NULL, 
    [Tel] NVARCHAR(200) NULL, 
	[Date] datetime NULL,
    [Description] NVARCHAR(500) NULL, 
	[CreateId] int  null,
	[CreateDate] DATETIME  NULL DEFAULT getdate(), 
	[UpdateId] int null,
	[UpdateDate] DATETIME ,
	[DeleteId] int null,
	[DeleteDate] DATETIME,
	[ReadOnly] DATETIME,
	[DocTypeId] INT NULL,
	[DocCertId] int null,
	[DocSeriesId] int null
	CONSTRAINT PKCustomer PRIMARY KEY (Id)
)
