CREATE TABLE [Accounting].[DocumentDetail]
(
	[Id] int NOT NULL IDENTITY, 
	[TotalId] int null,
	[PaymentId] int  null,
	[BarcodeId]  int null,
	[DocumentId] int  null,
	[AccountId] int null,
    [GoodId] INT NULL, 
    [Series] nvarchar(200) NULL, 
    [DateOfProduction] DATETIME NULL, 
    [LastExpirationDate] DATETIME NULL, 
	[Quantity] DECIMAL(26, 6)  NULL, 
	[StoQuantity] DECIMAL(26, 6)  NULL, 
	[UnitId] INT NULL,
    [PriceBuy] DECIMAL (26, 6) NULL, 
    [PriceRetail] DECIMAL (26, 6) NULL, 
    [PriceWholeSale] DECIMAL (26, 6) NULL, 
    [AmountBuy] DECIMAL (26, 6) NULL, 
    [AmountRetail] DECIMAL (26, 6) NULL, 
    [AmountWholeSale] DECIMAL (26, 6) NULL, 
	[Payment] DECIMAL(26, 6) NULL, 
	[Deficit] DECIMAL(26, 6) NULL, 
	[Description] nvarchar(500) null,
	--[DiscountPercent] decimal(26,6) null,
	[Percent] nvarchar(50),
	[DiscountNumber]NVARCHAR(500) NULL,	
	[DiscountNumberDeficit] decimal(26,6) null,
	[CostInclude]   decimal(26,6) null,
	[CostDeficit]   decimal(26,6) null,
	[DiscountPrice] decimal(26,6) null,
	[IsActive] bit default 1 not null,
	[SaleNo] int null,
	[CreateId] INT NULL,
	[CreateDate] DATETIME  NULL DEFAULT getdate(), 
	[UpdateId] int null,
	[UpdateDate] DATETIME ,
	[DeleteId] int null,
	[DeleteDate] DATETIME,
	[ReadOnly] DATETIME
	CONSTRAINT PKDocumentDetail PRIMARY KEY (Id)
    
)
